language: go
install:
 - go get github.com/arcticfoxnv/gopacket
 - go get github.com/arcticfoxnv/gopacket/layers
 - go get github.com/arcticfoxnv/gopacket/tcpassembly
script:
 - go test github.com/arcticfoxnv/gopacket
 - go test github.com/arcticfoxnv/gopacket/layers
 - go test github.com/arcticfoxnv/gopacket/tcpassembly
 - ./.travis.gofmt.sh
